---
- name: CliXX DB Deployment Ansible Playbook
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    db_instance_id: clixx-retaildb-restore
    db_snapshot_id: clixx-retaildb
    region: us-east-2

  tasks:

    - name: Restore DB from snapshot
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ db_instance_id }}"
        db_snapshot_identifier: "{{ db_snapshot_id }}"
        creation_source: snapshot
        db_instance_class: db.t4g.micro
        engine: mysql
        region: "{{ region }}"

        # Attach security group to DB
        vpc_security_group_ids:
          - "{{ security_group_id }}"
        db_subnet_group_name: "{{ db_subnet_group }}"
        publicly_accessible: false
        state: present
        wait: yes

